# Generated by Django 3.2.16 on 2023-01-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
